命令稿啟動於 2018年03月15日 下午 06:58:56
]0;~
[32muser@DESKTOP-PLSUEOI [33m~[0m
$ whoami;pwd
user
/home/user
]0;~
[32muser@DESKTOP-PLSUEOI [33m~[0m
$ git config -l[K[K[K[K[Kig -l
user.email=jetjet888@gmail.com
user.name=jetjet888
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
remote.jetjet888.url=https://github.com/jetjet888/lab1.git
remote.jetjet888.fetch=+refs/heads/*:refs/remotes/jetjet888/*
remote.lab1.url=https://github.com/jetjet888/lab1.git
remote.lab1.fetch=+refs/heads/*:refs/remotes/lab1/*
remote.origin.url=https://github.com/jetjet888/LAB1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;~
[32muser@DESKTOP-PLSUEOI [33m~[0m
$ git clone https://github.com/jetjet888/LAB1.git
Cloning into 'LAB1'...
warning: You appear to have cloned an empty repository.
]0;~
[32muser@DESKTOP-PLSUEOI [33m~[0m
$ exit

命令稿已於 2018年03月15日 下午 06:59:49
 完成