命令稿啟動於 2018年03月11日 下午 10:52:28
]0;~
[32muser@DESKTOP-PLSUEOI [33m~[0m
$ whoami;pwd
user
/home/user
]0;~
[32muser@DESKTOP-PLSUEOI [33m~[0m
$ git config -l
user.email=jetjet888@gmail.com
user.name=jetjet888
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
]0;~
[32muser@DESKTOP-PLSUEOI [33m~[0m
$ git clone https://github.com/jetjet888/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;~
[32muser@DESKTOP-PLSUEOI [33m~[0m
$ [K$ [K$ exit

命令稿已於 2018年03月11日 下午 10:53:43
 完成